export interface Book {
  key: string;
  title: string;
  author_name?: string[];
  cover_i?: number;
  first_publish_year?: number;
  language?: string[];
}

export const BOOKS: Book[] = [
  {
    key: "/works/OL66554W",
    title: "Pride and Prejudice",
    author_name: ["Jane Austen"],
    cover_i: 14348537,
    first_publish_year: 1813,
    language: ["en"],
  },
  {
    key: "/works/OL102749W",
    title: "Moby-Dick",
    author_name: ["Herman Melville"],
    cover_i: 10544254,
    first_publish_year: 1851,
    language: ["en"],
  },
  {
    key: "/works/OL262421W",
    title: "The Adventures of Sherlock Holmes",
    author_name: ["Arthur Conan Doyle"],
    cover_i: 6717853,
    first_publish_year: 1892,
    language: ["en"],
  },
  {
    key: "/works/OL8721462W",
    title: "Great Expectations",
    author_name: ["Charles Dickens"],
    cover_i: 13322313,
    first_publish_year: 1861,
    language: ["en"],
  },
  {
    key: "/works/OL267171W",
    title: "War and Peace",
    author_name: ["Leo Tolstoy"],
    cover_i: 12621906,
    first_publish_year: 1869,
    language: ["en"],
  },
  {
    key: "/works/OL17519279W",
    title: "Anna Karenina",
    author_name: ["Leo Tolstoy"],
    cover_i: 2560652,
    first_publish_year: 1877,
    language: ["en"],
  },
  {
    key: "/works/OL85892W",
    title: "Dracula",
    author_name: ["Bram Stoker"],
    cover_i: 12216503,
    first_publish_year: 1897,
    language: ["en"],
  },
  {
    key: "/works/OL450063W",
    title: "Frankenstein",
    author_name: ["Mary Shelley"],
    cover_i: 12356249,
    first_publish_year: 1818,
    language: ["en"],
  },
  {
    key: "/works/OL8193416W",
    title: "The Picture of Dorian Gray",
    author_name: ["Oscar Wilde"],
    cover_i: 14314858,
    first_publish_year: 1890,
    language: ["en"],
  },
  {
    key: "/works/OL138052W",
    title: "Alice's Adventures in Wonderland",
    author_name: ["Lewis Carroll"],
    cover_i: 10527843,
    first_publish_year: 1865,
    language: ["en"],
  },
  {
    key: "/works/OL151406W",
    title: "Through the Looking-Glass",
    author_name: ["Lewis Carroll"],
    cover_i: 8228693,
    first_publish_year: 1871,
    language: ["en"],
  },
  {
    key: "/works/OL20098701W",
    title: "The Count of Monte Cristo",
    author_name: ["Alexandre Dumas"],
    cover_i: 8091011,
    first_publish_year: 1844,
    language: ["en"],
  },
  {
    key: "mock-14",
    title: "Jane Eyre",
    author_name: ["Charlotte Brontë"],
    cover_i: 8224321,
    first_publish_year: 1847,
    language: ["en"],
  },
  {
    key: "mock-15",
    title: "Wuthering Heights",
    author_name: ["Emily Brontë"],
    cover_i: 8224333,
    first_publish_year: 1847,
    language: ["en"],
  },
  {
    key: "mock-16",
    title: "The Odyssey",
    author_name: ["Homer"],
    cover_i: 8231996,
    first_publish_year: -700,
    language: ["en"],
  },
  {
    key: "mock-17",
    title: "The Iliad",
    author_name: ["Homer"],
    cover_i: 8232002,
    first_publish_year: -750,
    language: ["en"],
  },
  {
    key: "mock-18",
    title: "Crime and Punishment",
    author_name: ["Fyodor Dostoevsky"],
    cover_i: 7984911,
    first_publish_year: 1866,
    language: ["en"],
  },
  {
    key: "mock-19",
    title: "The Brothers Karamazov",
    author_name: ["Fyodor Dostoevsky"],
    cover_i: 7984912,
    first_publish_year: 1880,
    language: ["en"],
  },
  {
    key: "mock-20",
    title: "Dr. Jekyll and Mr. Hyde",
    author_name: ["Robert Louis Stevenson"],
    cover_i: 8231992,
    first_publish_year: 1886,
    language: ["en"],
  },
  {
    key: "mock-21",
    title: "Gulliver's Travels",
    author_name: ["Jonathan Swift"],
    cover_i: 8231993,
    first_publish_year: 1726,
    language: ["en"],
  },
  {
    key: "mock-22",
    title: "The Divine Comedy",
    author_name: ["Dante Alighieri"],
    cover_i: 8231994,
    first_publish_year: 1320,
    language: ["en"],
  },
  {
    key: "mock-23",
    title: "A Tale of Two Cities",
    author_name: ["Charles Dickens"],
    cover_i: 8314144,
    first_publish_year: 1859,
    language: ["en"],
  },
  {
    key: "mock-24",
    title: "Macbeth",
    author_name: ["William Shakespeare"],
    cover_i: 8231995,
    first_publish_year: 1606,
    language: ["en"],
  },
  {
    key: "mock-25",
    title: "Hamlet",
    author_name: ["William Shakespeare"],
    cover_i: 8231997,
    first_publish_year: 1603,
    language: ["en"],
  },
  {
    key: "mock-26",
    title: "Romeo and Juliet",
    author_name: ["William Shakespeare"],
    cover_i: 8231998,
    first_publish_year: 1597,
    language: ["en"],
  },
  {
    key: "mock-27",
    title: "The Hobbit",
    author_name: ["J.R.R. Tolkien"],
    cover_i: 8231999,
    first_publish_year: 1937,
    language: ["en"],
  },
  {
    key: "mock-28",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    author_name: ["J.R.R. Tolkien"],
    cover_i: 8232000,
    first_publish_year: 1954,
    language: ["en"],
  },
  {
    key: "mock-29",
    title: "The Lord of the Rings: The Two Towers",
    author_name: ["J.R.R. Tolkien"],
    cover_i: 8232001,
    first_publish_year: 1954,
    language: ["en"],
  },
  {
    key: "mock-30",
    title: "The Lord of the Rings: The Return of the King",
    author_name: ["J.R.R. Tolkien"],
    cover_i: 8232002,
    first_publish_year: 1955,
    language: ["en"],
  },
];

export type Books = (typeof BOOKS)[number];
